import pyautogui, time, os

pyautogui.press("win")
pyautogui.typewrite("cmd")
pyautogui.press("enter")
pyautogui.typewrite("title hacker console")
pyautogui.press("enter")
pyautogui.typewrite("color a")
pyautogui.press("enter")
pyautogui.typewrite("cls")
pyautogui.press("enter")
pyautogui.typewrite("echo Welcome to Hacker Console By Otiopo")
pyautogui.press("enter")
pyautogui.typewrite("echo screen will be cleared at 1 second")
pyautogui.press("enter")
time.sleep(1)
pyautogui.typewrite("cd " + os.getcwd())
pyautogui.press("enter")
pyautogui.typewrite("prompt HackerConsole$B$T$B#$P$G")
pyautogui.press("enter")
pyautogui.typewrite("cls")
pyautogui.press("enter")
