import pyautogui, time, os

pyautogui.press("win")
time.sleep(0.2)
pyautogui.typewrite("cmd")
time.sleep(2)
pyautogui.press("enter")
time.sleep(1)
pyautogui.typewrite("title hacker console")
pyautogui.press("enter")
time.sleep(0.1)
pyautogui.typewrite("color a")
pyautogui.press("enter")
time.sleep(0.1)
pyautogui.typewrite("cls")
pyautogui.press("enter")
time.sleep(0.1)
pyautogui.typewrite("echo Welcome to Hacker Console")
pyautogui.press("enter")
time.sleep(0.1)
pyautogui.typewrite("echo screen will be cleared at 1 second")
pyautogui.press("enter")
time.sleep(1)
pyautogui.typewrite("cd " + os.getcwd())
pyautogui.press("enter")
time.sleep(0.1)
pyautogui.typewrite("prompt HackerConsole$B$T$B#$P$G")
pyautogui.press("enter")
time.sleep(0.1)
pyautogui.typewrite("cls")
pyautogui.press("enter")
